### ISSUE TITLE
lswolfe does not work with CudaTensors

### ISSUE THREAD

**Issue by bobbens** [torch/optim#75]
lswolfe uses torch.Tensor by default internally and does not work with CudaTensors. If you set the default tensor type to CudaTensor it still doesn't work. This prevents using line searches with lbfgs when using CudaTensors.

**Comment by woffle** [comment]
Hi has this been fixed?

**Comment by soumith** [comment]
fixed via https://github.com/torch/optim/commit/a959ba3fd6abb3526836b9e3ae514e2adc400dd6

**Comment by nafitzgerald** [comment]
I believe this is still not fixed because polyinterp.lua uses torch.Tensor in a few places (ie. line 197)

**Comment by soumith** [comment]
fixed via https://github.com/torch/optim/pull/138

**Comment by nafitzgerald** [comment]
Thanks for this, however, when I run the same code I was using before using CUDA, I now get the following error:



`** On entry to SORMQR parameter number 12 had an illegal value`
`On entry to magma_sgels_gpu, parameter 10 had an illegal value (info = -10)`
`/home/nfitz/torch/install/bin/lua: MAGMA gels : Argument 10 : illegal value at /home/nfitz/torch/extra/cutorch/lib/THC/THCTensorMathMagma.cu:156`
`stack traceback:`
`        [C]: ?`
`        [C]: in function 'gels'`
`        ...itz/torch/install/share/lua/5.1/optim/polyinterp.lua:170: in function 'polyinterp'`
`        .../nfitz/torch/install/share/lua/5.1/optim/lswolfe.lua:88: in function 'lineSearch'`
`        ...me/nfitz/torch/install/share/lua/5.1/optim/lbfgs.lua:202: in function 'lbfgs'`
`        vqaOptim.lua:245: in function 'train_epoch'`
`        vqaOptim.lua:173: in function 'runTrainVal'`
`        vqaOptim.lua:382: in main chunk`
`        [C]: in function 'dofile'`
`        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk`
`        [C]: ?`

By printing b and A on line 170 of polyinterp, I was able to isolate the bug with the following script:

```
require 'cutorch'

local b = torch.Tensor{{317.0087} ,{316.9857}, {-0.9324}, {-0.9319}}
local A = torch.Tensor{{0.0000, 0.0000, 0.0000, 1.0000},
{0.0000, 0.0006, 0.0246, 1.0000},
{0.0000, 0.0000, 1.0000, 0.0000},
{0.0018, 0.0492, 1.0000, 0.0000}}
print(b)
print(A)

print("MEM: ")
print(torch.gels(b,A))

print("CUDA: ")
print(torch.gels(b:cuda(), A:cuda()))

```

Which gives the following output:

```

$ th /tmp/test.lua 
 317.0087
 316.9857
  -0.9324
  -0.9319
[torch.DoubleTensor of size 4x1]

 0.0000  0.0000  0.0000  1.0000
 0.0000  0.0006  0.0246  1.0000
 0.0000  0.0000  1.0000  0.0000
 0.0018  0.0492  1.0000  0.0000
[torch.DoubleTensor of size 4x4]

MEM:    
   3.1460
  -0.1049
  -0.9324
 317.0087
[torch.DoubleTensor of size 4x1]

-0.0018 -0.0492 -1.0000  0.0000
 0.0000  0.0006  0.0246  1.0000
 0.0000  0.0000  1.0000  0.0000
 1.0000  0.0000  0.0000 -1.0000
[torch.DoubleTensor of size 4x4]

CUDA:   
 ** On entry to SORMQR parameter number 12 had an illegal value
On entry to magma_sgels_gpu, parameter 10 had an illegal value (info = -10)
/home/nfitz/torch/install/bin/lua: MAGMA gels : Argument 10 : illegal value at /home/nfitz/torch/extra/cutorch/lib/THC/THCTensorMathMagma.cu:156
stack traceback:
        [C]: ?
        [C]: in function 'gels'
        /tmp/test.lua:15: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: ?

```

Any ideas why this is happening?
